export const SET_CONFIG = 'SET_CONFIG';
export const SET_AUTH = 'SET_AUTH';
export const SET_CURRENT_ASSET = 'SET_CURRENT_ASSET';
export const SET_BASECAMP_USER = 'SET_BASECAMP_USER';
export const SET_USER_ID = 'SET_USER_ID';
export const SET_CLOUD_ACCOUNTS = 'SET_CLOUD_ACCOUNTS';
export const SET_MP_MODERATOR_MENU = 'SET_MP_MODERATOR_MENU';
export const SET_HIKE_ADMIN_MENU = 'SET_HIKE_ADMIN_MENU';
export const SET_PRIVATE_MODERATOR_MENU = 'SET_PRIVATE_MODERATOR_MENU';
export const SET_BASECAMP_SEARCH_RESULTS = 'SET_BASECAMP_SEARCH_RESULTS';
export const SET_VIZ_APP = 'SET_VIZ_APP';
export const SET_VIZ_WEB = 'SET_VIZ_WEB';
export const SET_VIZ_VERSION = 'SET_VIZ_VERSION';
export const SET_NFI_VERSION = 'SET_NFI_VERSION';
export const SET_USER_TYPE = 'SET_USER_TYPE';
export const SET_DID_YOU_MEAN = 'SET_DID_YOU_MEAN';

export const REQUEST_ASSETS = 'REQUEST_ASSETS';
export const UPDATE_ASSETS = 'UPDATE_ASSETS';
export const SET_ASSETS = 'SET_ASSETS';
export const SET_LOAD_MORE = 'SET_LOAD_MORE';
export const SET_ASSET_COUNT = 'SET_ASSET_COUNT';
export const SET_TOTAL_ASSET_COUNT = 'SET_TOTAL_ASSET_COUNT';
export const INCREMENT_ASSET_COUNT = 'INCREMENT_ASSET_COUNT';
export const SET_HEADERS = 'SET_HEADERS';
export const UPDATE_HEADERS = 'UPDATE_HEADERS';
export const SET_ASSETS_LOADING = 'SET_ASSETS_LOADING';


export const SET_FILTERS = 'SET_FILTERS';
export const SET_SELECTED_FILTERS = 'SET_SELECTED_FILTERS';
export const SET_FILTERS_LOADING = 'SET_FILTERS_LOADING';
